spring:
  datasource:
    url: jdbc:postgresql://orders-db:5432/ordersdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
logging:
  level:
    root: INFO
